#!/bin/sh /etc/rc.common

START=97
STOP=97
SERVICE=app
PROG=/usr/bin/qbittorrent-nox
USE_PROCD=1

start_service()
{
	echo service qbittorrent start
	procd_open_instance
	procd_set_param command $PROG --profile="/root/.config"
	procd_set_param respawn
	procd_close_instance
}
